### ISSUE TITLE
Building a new one referring to this project

### ISSUE THREAD

**Issue by awholeneworld** [nelsonjchen/droid-dicom-viewer#2]
It helped me a lot to make basic functions of DICOM viewer.
Since it does not show DICOM images properly, I used a library to fix that.

https://github.com/awholeneworld/MobileDicomViewer

Still work in progress.
Thank you.

**Comment by nelsonjchen** [comment]
I'm glad to hear it helped. Unfortunately, this project was made a lifetime ago. I'm going to archive this repository, but hopefully people who need a Android DICOM viewer can find your project via Google.
